# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Downloader": "Downloader.ipynb",
         "DownloaderError": "Downloader.ipynb",
         "ImageDownloader": "Downloader.ipynb",
         "GoogleImageDownloaderError": "Downloader.ipynb",
         "GoogleImageDownloader": "Downloader.ipynb",
         "ImageCleaner": "cleaner.ipynb",
         "app": "cli.ipynb",
         "scrap": "cli.ipynb",
         "parallel": "cli.ipynb",
         "cli": "cli.ipynb",
         "ParalelDownload": "paralel.ipynb",
         "TorchDataset": "torch_dataset.ipynb"}

modules = ["downloader.py",
           "cleaner.py",
           "cli.py",
           "paralel.py",
           "torch_dataset.py"]

doc_url = "https://samsja.github.io/web2dataset/"

git_url = "https://github.com/samsja/web2dataset/tree/main/"

def custom_doc_links(name): return None
