# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Downloader": "Downloader.ipynb",
         "BasicSearcher": "Downloader.ipynb",
         "DownloaderError": "Downloader.ipynb",
         "GoogleImageDownloaderError": "Downloader.ipynb",
         "GoogleImageDownloader": "Downloader.ipynb",
         "MetaDataCleanerError": "cleaner.ipynb",
         "check_no_docs_creation": "cleaner.ipynb",
         "MetaDataCleaner": "cleaner.ipynb",
         "IdentityCleaner": "cleaner.ipynb",
         "DuplicateCleaner": "cleaner.ipynb",
         "ImageCleaner": "cleaner.ipynb"}

modules = ["downloader.py",
           "cleaner.py"]

doc_url = "https://samsja.github.io/web2dataset/"

git_url = "https://github.com/samsja/web2dataset/tree/main/"

def custom_doc_links(name): return None
