# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MetaDataCleanerError": "cleaner.ipynb",
         "check_no_docs_creation": "cleaner.ipynb",
         "MetaDataCleaner": "cleaner.ipynb",
         "IdentityCleaner": "cleaner.ipynb",
         "DuplicateCleaner": "cleaner.ipynb",
         "ImageCleaner": "cleaner.ipynb",
         "Document": "document.ipynb",
         "Downloader": "downloader.ipynb",
         "BasicDownloader": "downloader.ipynb",
         "MultiThreadedDownloader": "downloader.ipynb",
         "Searcher": "searcher.ipynb",
         "SearchError": "searcher.ipynb",
         "GoogleImageSearchError": "searcher.ipynb",
         "GoogleImageSearcher": "searcher.ipynb"}

modules = ["cleaner.py",
           "document.py",
           "downloader.py",
           "searcher.py"]

doc_url = "https://samsja.github.io/web2dataset/"

git_url = "https://github.com/samsja/web2dataset/tree/main/"

def custom_doc_links(name): return None
