# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/cleaner.ipynb (unless otherwise specified).

__all__ = ['ImageCleaner']

# Cell
from abc import ABC, abstractmethod

# Cell
class ImageCleaner:
    def __init__(self, path: str):
        self.path = path

    def clean(self):
        pass