# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/cleaner.ipynb (unless otherwise specified).

__all__ = ['MetaDataCleaner', 'ImageCleaner']

# Cell
from typing import List

from .document import Document

# Cell
class MetaDataCleaner:
    def clean(self, docs : List[Document]) -> List[Document]:
        pass


# Cell
class ImageCleaner:
    def __init__(self, path: str):
        self.path = path

    def clean(self):
        pass