# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/cli.ipynb (unless otherwise specified).

__all__ = ['scrap', 'cli']

# Cell
from pathlib import Path
from typing import List

import typer

from .downloader import GoogleImageDownloader
from .paralel import ParalelDownload

# Cell
def scrap(
    n_item: int = typer.Argument(..., help="The number of element you want to scrap"),
    queries: List[str] = typer.Argument(..., help="The queries for your scrapping"),
    path: Path = typer.Argument(
        Path("."), help="The folder where to download the dataset"
    ),
    num_workers: int = typer.Argument(4, help="The number of worker"),
):
    if len(queries) == 1:
        GoogleImageDownloader(str(path)).download(queries[0])
    else:
        num_workers = min(num_workers, len(queries))
        ParalelDownload(
            str(path), GoogleImageDownloader, num_workers=num_workers
        ).download(list(queries), n_item)

# Cell

def cli():
    typer.run(scrap)


if __name__ == "__main__":
    from IPython import get_ipython

    if not get_ipython():
        cli()
    else:
        print("running in a notebook")