# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/document.ipynb (unless otherwise specified).

__all__ = ['Document']

# Cell
from datetime import datetime
from zoneinfo import ZoneInfo

# Cell
class Document:
    def __init__(self, origin: str, timezone: ZoneInfo = ZoneInfo("Europe/Paris")):
        self.date = datetime.now(timezone)
        self.origin = origin