# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/document.ipynb (unless otherwise specified).

__all__ = ['Document']

# Cell
import uuid
from datetime import datetime
from typing import Optional
from zoneinfo import ZoneInfo

import jsons

# Cell
class Document:
    def __init__(
        self,
        origin: str,
        timezone: ZoneInfo = ZoneInfo("Europe/Paris"),
        image_url: Optional[str] = None,
    ):
        self.date = datetime.now(timezone)
        self.origin = origin
        self.image_url = image_url
        self.uuid = uuid.uuid1()

    def __repr__(self):
        return jsons.dumps(self)