# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/downloader.ipynb (unless otherwise specified).

__all__ = ['Downloader', 'BasicDownloader', 'MultiThreadedDownloader']

# Cell
class Downloader:
    def __init__(path: str):
        self.path = path

    def download(self, data_uri: str):
        pass

# Cell
class BasicDownloader(Downloader):
    pass

# Cell
class MultiThreadedDownloader(Downloader):
    pass