# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/downloader.ipynb (unless otherwise specified).

__all__ = ['Downloader', 'BasicDownloader', 'MultiThreadedDownloader']

# Cell
from abc import ABC, abstractmethod

# Cell
class Downloader(ABC):
    def __init__(path: str):
        self.path = path

    @abstractmethod
    def download(self, data_uri: str):
        pass

# Cell
class BasicDownloader(Downloader):
    pass

# Cell
class MultiThreadedDownloader(Downloader):
    pass