# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/downloader.ipynb (unless otherwise specified).

__all__ = ['Downloader', 'DonwloaderError', 'PathError', 'BasicDownloader', 'MultiThreadedDownloader']

# Cell
import json
import os
import shutil
import urllib
from abc import ABC, abstractmethod
from typing import List

import jsons
from PIL import Image

from .document import Document

# Cell
class Downloader(ABC):
    def __init__(self, path: str):
        self.path = path
        self.documents = self._init_docs(self.path)
        self._init_download()

    def _init_download(self):
        self.images_path = f"{self.path}/images"

        if not os.path.isdir(self.images_path):
            os.mkdir(self.images_path)

    def _file_to_docs(self, path_to_file) -> Document:
        with open(path_to_file) as json_file:
            data = json.load(json_file)

        return jsons.load(data, Document)

    def _init_docs(self, path: str) -> List[Document]:

        self.metadata_path = f"{path}/metadata"
        if not os.path.isdir(self.metadata_path):
            raise PathError(f"not metadata subfolder in {path}")

        file_docs = os.listdir(self.metadata_path)

        return [
            self._file_to_docs(f"{self.metadata_path}/{file}") for file in file_docs
        ]

    @abstractmethod
    def download(self):
        pass

# Cell
class DonwloaderError(ValueError):
    pass

class PathError(DonwloaderError):
    pass

# Cell
class BasicDownloader(Downloader):
    def download(self):

        for doc in self.documents:
            if doc.image_url is None or len(doc.image_url) < 4:
                pass
            elif doc.image_url[0:4] == "data":
                # In some case like with the GoogleImageSearcher the json file have already donwload the data Therefore
                # we don't need to donwload but to move the data from the json
                self._move_image_from_json(doc)
            else:
                self._download_single_file(doc.image_url, self._path_to_file(doc))

    def _path_to_file(self, doc: Document) -> str:
        return f"{self.images_path}/{doc.uuid}"

    def _download_single_file(self, url: str, path_to_file: str):

        try:
            data = urllib.request.urlopen(url)
            with open(f"{path_to_file}", "wb") as fp:
                fp.write(data.read())

        except urllib.error  as e:
            print(f"unable to donwload {path_to_file}, following error {e}")

    def _move_image_from_json(self, doc: Document):

        try:
            with open(self._path_to_file(doc), "wb") as fp:
                data = urllib.request.urlopen(doc.image_url)
                fp.write(data.file.read())
        except urllib.error  as e:
            print(e)

        doc.image_url = None

        with open(f"{self.path}/metadata/{doc.uuid}.json", "w") as fp:
            json.dump(jsons.dump(doc), fp)

# Cell
class MultiThreadedDownloader(Downloader):
    pass