# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/searcher.ipynb (unless otherwise specified).

__all__ = ['Searcher']

# Cell
class Searcher:
    def __init__(self, query: str):
        self.query = query
        self.data_uri = []

    def search(self):
        pass